using Common;
using Common.Dtos;
using System.Diagnostics;
using System.IO;

namespace Data
{
    public class PythonUtility
    {

        public static PythonResultDto<string> ExecutePythonScript(PythonRequestDto request)
        {
            var cmd = request.Command; // "understats2.py";
            var workingDirectory = Utility.GetApplicationSetting<string>("WorkingDirectory");
            var pathToPythonExecutable = Utility.GetApplicationSetting<string>("PathTopythonExe");

            var pythonResult = new PythonResultDto<string>
            {
                Status = false
            };

            ProcessStartInfo start = new ProcessStartInfo();
            start.WorkingDirectory = workingDirectory;
            start.FileName = pathToPythonExecutable;
            start.Arguments = string.Format("\"{0}\" \"{1}\" \"{2}\"", cmd, request.Params[0], request.Params[1]);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)

            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")

                    pythonResult.Status = stderr == "";
                    pythonResult.ErrorMessage = stderr;
                    pythonResult.Output = result.StripLineBreaks();
                }
            }

            return pythonResult;
        }
    }
}
