using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace Data
{
    public class ScrapingUtility
    {
        public static readonly string WORKING_DIRECTORY = "D:\\repos\\FPLStats\\FPLStats\\FantasyStats\\Data\\Scraping";
        public static readonly string PATH_TO_PYTHONEXE = "C:\\Python34\\python.exe";

        public static bool ExecuteScrapingUtility(int year)
        {
            var cmd = "understats2.py";

            ProcessStartInfo start = new ProcessStartInfo();
            start.WorkingDirectory = WORKING_DIRECTORY;
            start.FileName = PATH_TO_PYTHONEXE;
            start.Arguments = string.Format("\"{0}\" \"{1}\"", cmd, year);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)

            var status = false;

            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")

                    status = stderr == "";
                }
            }


            return status;
        }
    }
}
