// <auto-generated />
namespace DataManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class new_calc_value : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_calc_value));
        
        string IMigrationMetadata.Id
        {
            get { return "201812090913278_new_calc_value"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
