// <auto-generated />
namespace DataManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changed_reference_to_position : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_reference_to_position));
        
        string IMigrationMetadata.Id
        {
            get { return "201811110824482_changed_reference_to_position"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
