// <auto-generated />
namespace DataManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_setting_and_teamstatistics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_setting_and_teamstatistics));
        
        string IMigrationMetadata.Id
        {
            get { return "201811170757500_added_setting_and_teamstatistics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
